[package]
name = "rustling-ontology-values"
version = "0.12.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
regex = "0.2"
rustling-ontology-moment = { path="../moment"}
rustling = { git="http://github.com/snipsco/rustling", rev="0.5.0" }
