[package]
name = "rustling-ontology-values"
version = "0.16.1"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
regex = "0.2"
rustling-ontology-moment = { path="../moment"}
rustling = { git="http://github.com/snipsco/rustling", tag="0.8.1" }
