[package]
name = "rustling-ontology-values"
version = "0.5.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
rustling-ontology-moment = { path="../moment"}
rustling = { git="http://github.com/snipsco/rustling", rev="0.3.0" }
