[package]
name = "rustling-ontology-ko"
version = "0.16.3"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
regex = "0.2"
rustling = { git="http://github.com/snipsco/rustling", tag="0.8.1" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}