[package]
name = "rustling-ontology"
version = "0.1.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[workspace]
members=["cli", "moment"]

[dependencies]
rustling = { git="http://github.com/snipsco/rustling", rev="4e60ef317eac27f788afe982b67b35ef027bf1f9" }

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "example"
harness = false
