[package]
name = "rustling-ontology"
version = "0.1.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]
build = "build.rs"

[workspace]
members=["cli", "moment", "rules", "training"]

[dependencies]
bincode = "0.8"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
rustling = { git="http://github.com/snipsco/rustling", rev="ab7bbbc" }
rustling-ontology-moment = { path="moment"}
rustling-ontology-rules = { path="rules"}
rustling-ontology-training = { path="training"}

[dev-dependencies]
bencher = "0.1"

[build-dependencies]
bincode = "0.8"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
rustling = { git="http://github.com/snipsco/rustling", rev="ab7bbbc" }
rustling-ontology-moment = { path="moment"}
rustling-ontology-rules = { path="rules"}
rustling-ontology-training = { path="training"}

[[bench]]
name = "example"
harness = false
