[package]
name = "rustling-ontology-ja"
version = "0.15.3"
authors = ["Anaïs <anais@chanclu.fr>"]

[dependencies]
regex = "0.2"
rustling = { git="http://github.com/snipsco/rustling", tag="0.8.1" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}