[package]
name = "rustling-ontology-de"
version = "0.16.1"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
rustling = { git="http://github.com/snipsco/rustling", tag="0.8.1" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}