[package]
name = "rustling-ontology-en"
version = "0.17.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
rustling = { git="https://github.com/snipsco/rustling", tag="0.8.1" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}