[package]
name = "rustling-cli"
version = "0.16.3"
authors = ["hdlj <hubert.delajonquiere@snips.net>", "Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
rustling-ontology = { path = ".."}
prettytable-rs = "0.6"
clap = "2"
