[package]
name = "rustling-ontology-training"
version = "0.11.1"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
rustling = { git="http://github.com/snipsco/rustling", rev="0.4.2" }
rustling-ontology-values = { path="../values" }
rustling-ontology-rules = { path="../rules" }
rustling-ontology-moment = { path = "../moment" }
