[package]
name = "rustling-ontology-training"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
rustling = { git="http://github.com/snipsco/rustling", rev="ab7bbbc" }
rustling-ontology-rules = { path="../rules" }
rustling-ontology-moment = { path = "../moment" }
