[package]
name = "rustling-ontology-moment"
version = "0.17.2"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
chrono = "0.3"
enum_primitive = "0.1.1"
vec_map = "0.8"
derive-new = "0.5"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "example"
harness = false
