[package]
name = "rustling-ontology-moment"
version = "0.1.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
chrono = "0.3"
enum_primitive = "0.1.1"
vec_map = "0.7.0"
derive-new = "0.4"
