[package]
name = "rustling-ontology-rules"
version = "0.6.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
rustling = { git="http://github.com/snipsco/rustling", rev="0.3.0" }
rustling-ontology-moment = { path="../moment"}
rustling-ontology-values = { path="../values"}
